routes/web.php
<?php

use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\AhpController;
use App\Http\Controllers\TopsisController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::name('mahasiswa.')->prefix('/mahasiswa')->namespace('Mahasiswa')->group(function () {
    Route::get('/mahasiswa', [MahasiswaController::class, 'index'])->name('index');
    Route::get('/mahasiswa/create', [MahasiswaController::class, 'create'])->name('create');
    Route::post('/mahasiswa/store', [MahasiswaController::class, 'store'])->name('store');
    Route::get('/mahasiswa/edit/{mahasiswa}', [MahasiswaController::class, 'edit'])->name('edit');
    Route::put('/mahasiswa/update/{mahasiswa}', [MahasiswaController::class, 'update'])->name('update');
    Route::delete('/mahasiswa/destroy/{mahasiswa}', [MahasiswaController::class, 'destroy'])->name('destroy');
});

Route::name('ahp.')->prefix('/ahp')->namespace('Ahp')->group(function () {
    Route::get('/ahp', [AhpController::class, 'index'])->name('index');
    Route::get('/ahp/create', [AhpController::class, 'create'])->name('create');
    Route::post('/ahp/store', [AhpController::class, 'store'])->name('store');
    Route::get('/ahp/edit/{ahp}', [AhpController::class, 'edit'])->name('edit');
    Route::put('/ahp/update/{ahp}', [AhpController::class, 'update'])->name('update');
    Route::delete('/ahp/destroy/{ahp}', [AhpController::class, 'destroy'])->name('destroy');
});

Route::name('topsis.')->prefix('/topsis')->namespace('Topsis')->group(function () {
    Route::get('/topsis', [TopsisController::class, 'index'])->name('index');
    Route::get('/topsis/create', [TopsisController::class, 'create'])->name('create');
    Route::post('/topsis/store', [TopsisController::class, 'store'])->name('store');
    Route::get('/topsis/edit/{topsis}', [TopsisController::class, 'edit'])->name('edit');
    Route::put('/topsis/update/{topsis}', [TopsisController::class, 'update'])->name('update');
    Route::delete('/topsis/destroy/{topsis}', [TopsisController::class, 'destroy'])->name('destroy');
});

app/Models/Mahasiswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Kelas;

class Mahasiswa extends Model
{
    use HasFactory;

    protected $table = 'mahasiswa';

    protected $guarded = ['
        id, created_at, updated_at
    '];

    public function kelas()
    {
        return $this->hasOne(Kelas::class, 'id', 'kelas_id');
    }
}

app/Http/Controllers/MahasiswaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Mahasiswa;
use App\Models\Kelas;
use Illuminate\Http\Request;

class MahasiswaController extends Controller
{
    public function index()
    {
        $list_mahasiswa = Mahasiswa::with('kelas')->get();
        return view('mahasiswa.index', compact('list_mahasiswa'));
    }

    public function create()
    {
        $list_sikap = [
            ['id' => 1, 'nama' => 'Buruk'],
            ['id' => 2, 'nama' => 'Kurang Baik'],
            ['id' => 3, 'nama' => 'Cukup'],
            ['id' => 4, 'nama' => 'Baik'],
            ['id' => 5, 'nama' => 'Sangat Baik'],
        ];

        return view('mahasiswa.form', compact('list_sikap'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'nama' => ['required', 'max:100'],
            'sikap' => ['required', 'numeric'],
            'pengetahuan' => ['required', 'numeric'],
            'keterampilan' => ['required', 'numeric'],
        ]);

        $list_sikap = [
            ['id' => 1, 'nama' => 'Buruk'],
            ['id' => 2, 'nama' => 'Kurang Baik'],
            ['id' => 3, 'nama' => 'Cukup'],
            ['id' => 4, 'nama' => 'Baik'],
            ['id' => 5, 'nama' => 'Sangat Baik'],
        ];

        $count = Mahasiswa::count()+1;
        $alternatif = 'A'.$count;

        $mahasiswa = Mahasiswa::firstOrCreate([
            'nama' => $request->nama,
            'alternatif' => $alternatif
        ]);

        if ($request->pengetahuan >= 95) {
            $pengetahuan = 5;
        }elseif ($request->pengetahuan >= 90) {
            $pengetahuan = 4;
        }elseif ($request->pengetahuan >= 85) {
            $pengetahuan = 3;
        }elseif ($request->pengetahuan >= 80) {
            $pengetahuan = 2;
        }else {
            $pengetahuan = 1;
        }

        if ($request->keterampilan >= 95) {
            $keterampilan = 5;
        }elseif ($request->keterampilan >= 90) {
            $keterampilan = 4;
        }elseif ($request->keterampilan >= 85) {
            $keterampilan = 3;
        }elseif ($request->keterampilan >= 80) {
            $keterampilan = 2;
        }else {
            $keterampilan = 1;
        }

        if ($mahasiswa->wasRecentlyCreated) {
            $mahasiswa->update([
                'sikap' => $list_sikap[$request->sikap-1]['nama'],
                'sikap_bobot' => $request->sikap,
                'pengetahuan' => $request->pengetahuan,
                'pengetahuan_bobot' => $pengetahuan,
                'keterampilan' => $request->keterampilan,
                'keterampilan_bobot' => $keterampilan,
            ]);
            return redirect()->route('mahasiswa.index')->withSuccess('Mahasiswa '.$request->nama.' berhasil ditambahkan');
        }else{
            return redirect()->back()->withErrors('Mahasiswa '.$request->nama.' sudah ada');
        }
    }

    public function edit($id)
    {
        $mahasiswa = Mahasiswa::find($id);

        $list_sikap = [
            ['id' => 1, 'nama' => 'Buruk'],
            ['id' => 2, 'nama' => 'Kurang Baik'],
            ['id' => 3, 'nama' => 'Cukup'],
            ['id' => 4, 'nama' => 'Baik'],
            ['id' => 5, 'nama' => 'Sangat Baik'],
        ];

        return view('mahasiswa.form', compact('list_sikap', 'mahasiswa'));
    }

    public function update($id, Request $request)
    {
        $request->validate([
            'nama' => ['required', 'max:100'],
            'pengetahuan' => ['required', 'numeric'],
            'keterampilan' => ['required', 'numeric'],
        ]);

        $list_sikap = [
            ['id' => 1, 'nama' => 'Buruk'],
            ['id' => 2, 'nama' => 'Kurang Baik'],
            ['id' => 3, 'nama' => 'Cukup'],
            ['id' => 4, 'nama' => 'Baik'],
            ['id' => 5, 'nama' => 'Sangat Baik'],
        ];

        if ($request->pengetahuan >= 95) {
            $pengetahuan = 5;
        }elseif ($request->pengetahuan >= 90) {
            $pengetahuan = 4;
        }elseif ($request->pengetahuan >= 85) {
            $pengetahuan = 3;
        }elseif ($request->pengetahuan >= 80) {
            $pengetahuan = 2;
        }else {
            $pengetahuan = 1;
        }

        if ($request->keterampilan >= 95) {
            $keterampilan = 5;
        }elseif ($request->keterampilan >= 90) {
            $keterampilan = 4;
        }elseif ($request->keterampilan >= 85) {
            $keterampilan = 3;
        }elseif ($request->keterampilan >= 80) {
            $keterampilan = 2;
        }else {
            $keterampilan = 1;
        }

        $mahasiswa = Mahasiswa::find($id)->update([
            'nama' => $request->nama,
            'pengetahuan' => $request->pengetahuan,
            'pengetahuan_bobot' => $pengetahuan,
            'keterampilan' => $request->keterampilan,
            'keterampilan_bobot' => $keterampilan,
        ]);

        if ($request->sikap) {
            $mahasiswa = Mahasiswa::find($id)->update([
                'sikap' => $list_sikap[$request->sikap-1]['nama'],
                'sikap_bobot' => $request->sikap,
            ]);
        }

        if ($mahasiswa) {
            return redirect()->route('mahasiswa.index')->withSuccess('Mahasiswa '.$request->nama.' berhasil disimpan');
        }else{
            return redirect()->back()->withErrors('Mahasiswa '.$request->nama.' gagal disimpan');
        }
    }

    public function destroy($id)
    {
        $mahasiswa = Mahasiswa::find($id);
        if ($mahasiswa) {
            $mahasiswa->delete();
            return redirect()->back()->withSuccess('Mahasiswa '.$mahasiswa->nama.' berhasil dihapus');
        }else{
            return redirect()->back()->withErrors('Mahasiswa '.$mahasiswa->nama.' tidak ditemukan');
        }
    }
}

resources/views/mahasiswa/form.blade.php
@extends('_layouts.default')
@section('content')
  <div>
    <div class="my-8">
      <div class="w-full flex flex-wrap justify-between py-4">
        <h1>{{ isset($mahasiswa)? 'Ubah' : 'Tambah' }} Mahasiswa</h1>
        <a href="{{ route('mahasiswa.index') }}" class="flex space-x-2 text-blue-500 hover:text-blue-800">
          Kembali
        </a>
      </div>
      <form action="{{ isset($mahasiswa)? route('mahasiswa.update', $mahasiswa->id) : route('mahasiswa.store') }}" method="POST"
        class="capitalize bg-white rounded-lg p-5"
      >
      @csrf
      @method(isset($mahasiswa)? 'PUT' : 'POST')
        <div class="flex justify-end items-center space-x-4 px-5 py-5">
          <label for="nama">nama</label>
          <input type="text" value="{{ isset($mahasiswa)? $mahasiswa->nama:'' }}" name="nama" class="rounded-md px-4 py-2 block border border-gray-200 lg:w-3/5">
        </div>
        <div class="flex justify-end items-center space-x-4 px-5 pb-5">
          <label for="sikap">sikap</label>
          <select name="sikap" id="sikap" class="rounded-md px-4 py-2 block border border-gray-200 lg:w-3/5">
            <option value="">Pilih Sikap</option>
            @foreach ($list_sikap as $index => $sikap)
              <option value="{{ $sikap['id'] }}">{{ $sikap['nama'] }}</option>
            @endforeach
          </select>
        </div>
        <div class="flex justify-end items-center space-x-4 px-5 pb-5">
          <label for="pengetahuan">pengetahuan</label>
          <input type="text" value="{{ isset($mahasiswa)? $mahasiswa->pengetahuan:'' }}" name="pengetahuan" class="rounded-md px-4 py-2 block border border-gray-200 lg:w-3/5">
        </div>
        <div class="flex justify-end items-center space-x-4 px-5 pb-5">
          <label for="keterampilan">keterampilan</label>
          <input type="text" value="{{ isset($mahasiswa)? $mahasiswa->keterampilan:'' }}" name="keterampilan" class="rounded-md px-4 py-2 block border border-gray-200 lg:w-3/5">
        </div>
        <div class="border-t border-gray-200 -mx-5 flex justify-end items-center pt-5 px-10">
          <button type="submit" class="px-4 py-2 bg-green-500 hover:bg-green-800 rounded-md text-white">simpan</button>
        </div>
      </form>
    </div>
  </div>
@endsection

resources/views/mahasiswa/index.blade.php
@extends('_layouts.default')
@section('content')
<div>
  <div class="py-2">
    <h1 class="text-lg font-semibold my-5 flex justify-between items-center">
      Daftar Mahasiswa
      <a href="{{ route('mahasiswa.create') }}"
        class="px-4 py-2 bg-blue-500 rounded-md text-white hover:bg-blue-700 text-base"
      >
        Tambah Mahasiswa
      </a>
    </h1>
    <div class="flex justify-center max-w-7xl rounded inline-block align-middle shadow">
      <table class="min-w-full">
        <thead>
          <tr>
            <th class="px-6 py-3 border-b tracking-wider uppercase leading-4 bg-gray-100 border-gray-200 text-sm">Alternatif</th>
            <th class="px-6 py-3 border-b tracking-wider uppercase leading-4 bg-gray-100 border-gray-200 text-sm">Nama</th>
            <th class="px-6 py-3 border-b tracking-wider uppercase leading-4 bg-gray-100 border-gray-200 text-sm">Sikap</th>
            <th class="px-6 py-3 border-b tracking-wider uppercase leading-4 bg-gray-100 border-gray-200 text-sm">Pengetahuan</th>
            <th class="px-6 py-3 border-b tracking-wider uppercase leading-4 bg-gray-100 border-gray-200 text-sm">Keterampilan</th>
            <th class="px-6 py-3 border-b tracking-wider uppercase leading-4 bg-gray-100 border-gray-200 text-sm"></th>
          </tr>
        </thead>
        <tbody>
          @forelse ($list_mahasiswa as $mahasiswa)
            <tr class="bg-gray-50 hover:bg-gray-100">
              <td class="px-6 py-3 leading-5 tracking-wider border-b border-gray-200 text-center whitespace-normal">
                {{ $mahasiswa->alternatif }}
              </td>
              <td class="px-6 py-3 leading-5 tracking-wider border-b border-gray-200 whitespace-normal">
                {{ $mahasiswa->nama }}
              </td>
              <td class="px-6 py-3 leading-5 tracking-wider border-b border-gray-200 text-center whitespace-normal">
                {{ $mahasiswa->sikap }}
              </td>
              <td class="px-6 py-3 leading-5 tracking-wider border-b border-gray-200 text-center whitespace-normal">
                {{ $mahasiswa->pengetahuan }}
              </td>
              <td class="px-6 py-3 leading-5 tracking-wider border-b border-gray-200 text-center whitespace-normal">
                {{ $mahasiswa->keterampilan }}
              </td>
              <td class="px-6 py-3 leading-5 tracking-wider border-b border-gray-200 text-center whitespace-normal text-white">
                <div class="flex space-x-3">
                  <a href="{{ route('mahasiswa.edit', $mahasiswa->id) }}"
                    class="px-4 py-2 rounded-md bg-indigo-600 hover:bg-indigo-700"
                  >
                    Edit
                  </a>
                  <form action="{{ route('mahasiswa.destroy', $mahasiswa->id) }}" method="POST">
                    @method('DELETE')
                    @csrf
                    <button type="submit"
                    class="px-4 py-2 rounded-md bg-red-600 hover:bg-red-700"
                    >
                      Delete
                    </button>
                  </form>
                </div>
              </td>
            </tr>
            @empty
            <tr class="bg-gray-50 hover:bg-gray-100 capitalize">
              <td colspan="7" class="px-6 py-3 leading-5 tracking-wider border-b border-gray-200 text-center whitespace-normal">
                tidak ada data mahasiswa
              </td>
            </tr>
          @endforelse
        </tbody>
      </table>
    </div>
  </div>
</div>
@endsection